# Development Docker Compose
services:
  risko-api:
    build: 
      context: .
      dockerfile: backend/Dockerfile.dev
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - DATABASE_URL=sqlite:///./risko.db
    volumes:
      - ./backend:/app/backend
      - ./frontend:/app/frontend
      - ./backend/.env:/app/backend/.env
    working_dir: /app/backend
    restart: unless-stopped

  postgres:
    image: postgis/postgis:15-3.3
    environment:
      - POSTGRES_DB=risko_dev
      - POSTGRES_USER=risko_user
      - POSTGRES_PASSWORD=risko_password
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    restart: unless-stopped

volumes:
  postgres_dev_data: