name: Deploy Frontend to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare deploy folder
        run: |
          mkdir -p out
          if [ -d "frontend" ]; then
            # copy all files preserving permissions and hidden files
            cp -a frontend/. out/
          else
            cp index.html out/index.html
          fi
          echo "Deploy folder contents:"
          ls -la out || true

      - name: Deploy to gh-pages branch (via action)
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: out
          clean: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
