name: Deploy Frontend to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare deploy folder
        run: |
          mkdir -p out
          if [ -d "frontend" ]; then
            cp -R frontend/* out/
          else
            cp index.html out/index.html
          fi

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./out

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
